### PR TITLE
add battery & little fix

### PR DESCRIPTION
**Pull request by dreampiggy**
1. use IOKit for OS X battery (charging, chargingTime,
   dischargingTime,level)
2. attention: `Promise` is not built-in some broswer so I don’t use
   standard API “getBattery()->Promise”
   it’s more about the JavaScript side, so we don’t need build a `Promise`
   in OC or Swift(but..I’m not familiar with both)
3. just fix a little typo and duplicate code

### CODE REVIEW

**Comment by dreampiggy** [comment]
Finally, hey diyde, long time no see(from that `UniqueHack`). An iOS project with web technique, interesting. Hope that you can build this project with more maintainability and efficiency. 

The first important thing is that you should not put all source code into one file and even one class..Some assist code like that `MakeNotification` should move to another class.

And also, `Swift` is a secure language with `Optional`, so many unwrap without check may cause fatal error or memory leak(especially that you use `unsafeBitCast` to convert to a raw pointer). Try spending a hour to read the <The Swift Programing Language> and use `guard` `if let chain` `try` to avoid in the future

Finally, Happy New Year :p

**Comment by djyde** [comment]
Hey, zhuoli. Thanks for your feedback and pull request.

The reason why we support standard API is that we want to support every web applications which are using standard API (like `Notification`). Imaging that as an average user, I do not need to code for implementing the notification (Web Wechat, for example).

Actually I AM a layman in Cocoa and Swift. I made WebShell because it is what I need and I think I should share with others. I made it by learning `Cocoa Framework` and `Swift` in two days. But the power of community will make it better. :)

Happy new year :D

**Comment by dreampiggy** [comment]
…OK, I think you misunderstand my means for this PR. I wrote the native side Swift code to get OS X battery info for Battery API usage (`charing`, `chargingTime`, `dischargingTime` and `level`)

You can now use `navigator.getBattery()` from any page or console to get an Object with this 4 property.

But there are some compitabilities for browser, [the standard(click here)](https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API) `navigator.getBattery()`will return a `Promise Object` which will redeemed this actually Object with 4 property. But I'm not familiar with front side JavaScript and I think we can just put a easy implement like Inject Promise.js(or not) and use `navigator.getBattery = Promise.resolve(navigator.battery.getBattery())`

But for more API like `Event Listener`, maybe there will use many JavaScript code to hook. So I leave this job to you(:p) bacause you are more fit for this.

**Comment by dreampiggy** [comment]
I test it in Xcode 7.2 on El Capitan,if the code don't work, you can `ping` me again :p

For JavaScript side hook, `Event Listener` can just use `multiple invoke` `getBattery()` to return a new Object (fot the future we can find some more efficient solution, such like async callback)

**Comment by djyde** [comment]
@wdg how do you think about it?

**Comment by 0xWDG** [comment]
I have tested it, it`s working great.
The code looks nice and it is a nice addition.

**Comment by dreampiggy** [comment]
@wdg Thanks. I use the `JSExport` interface to bind Swift Battery Object withe JavaScript Object, because it's easy to understand, manage and easy to fix. (we can make a group called JSBridge and put all the JSExport class into it) and we don't need any cast but only one line code:

``` swift
jsContext.objectForKeyedSubscript("navigator").setObject(BatteryManager.self, forKeyedSubscript: "battery")
```

``` swift
let myNofification: @convention(block) (NSString!, NSString?, NSString?) -> Void = { (title:NSString!, message:NSString?, icon:NSString?) in
            self.makeNotification(title, message: message!, icon: icon!) // here 
        }
jsContext.objectForKeyedSubscript("Notification").setObject(unsafeBitCast(myNofification, AnyObject.self), forKeyedSubscript:"note")
```

But, put an the `JSExport` into a temp block and use `unsafeBitCast` is really dangerous, for Swift doc ,it says

> func unsafeBitCast<T, U>(x: T, _: U.Type) -> U
> 
> Returns the the bits of x, interpreted as having type U.
> 
> Warning: Breaks the guarantees of Swift's type system; use with extreme care. There's almost always a better way to do anything.

cast a block to AnyObject will not throw a error, because the size of `AnyObject` is large than `Objective-C block`, but it will cause something strange if you continue cast this AnyObject back or some other Object..(maybe memory leak or dirty write)

That's why I use a `JSExport` interface and separate .swift file. You can also just put the code into ViewController.swift if you prefer. Don't forget to import `IOKit.ps` :p

**Pull request merged**
